language: node_js

node_js:
  - node

cache:
  yarn: true
  directories:
    - node_modules

branches:
  only:
    - master

# after_script:
  # - cat coverage/lcov.info | node_modules/.bin/coveralls
