addons:
  chrome: beta

language: node_js

node_js:
  - node

script: eslint src && npm t

cache:
  yarn: true
  directories:
    - node_modules

branches:
  only:
    - master

# after_script:
  # - cat coverage/lcov.info | node_modules/.bin/coveralls

env:
  - CHROME_PATH=/usr/bin/google-chrome-beta
